# Generated by Django 5.2.5 on 2026-01-13 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=30, verbose_name='Модель авто')),
                ('car_number', models.CharField(max_length=20, verbose_name='Номер машини')),
                ('is_online', models.BooleanField(default=False, verbose_name='Онлайн')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
