# Generated by Django 5.2.5 on 2026-01-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_alter_driver_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
    ]
