# Generated by Django 5.2.5 on 2026-01-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driver_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='city',
            field=models.CharField(default='Не вказано', max_length=50),
            preserve_default=False,
        ),
    ]
