# Generated by Django 5.2.5 on 2026-02-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_alter_driver_rating_driverrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='driver',
            name='bonus_for_paid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
