# Generated by Django 5.2.5 on 2026-02-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0007_driver_balance_driver_bonus_for_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='rating_bonus_for_paid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
