# Generated by Django 5.2.5 on 2026-02-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0010_alter_driver_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='ride_500_for_paid',
            field=models.BooleanField(default=False),
        ),
    ]
