# Generated by Django 5.2.5 on 2026-01-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_taxiorder_comment_taxiorder_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxiorder',
            name='city',
            field=models.CharField(default='немає', max_length=100),
            preserve_default=False,
        ),
    ]
