# Generated by Django 5.2.5 on 2026-01-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_taxiorder_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxiorder',
            name='status',
            field=models.CharField(choices=[('searching', 'Пошук водія'), ('accepted', 'Accepted'), ('on_the_way', 'В дорозі'), ('arrived', 'Прибув'), ('completed', 'Завершено'), ('cancelled', 'Скасовано')], default='searching', max_length=20),
        ),
    ]
