# Generated by Django 5.2.5 on 2026-02-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_taxiorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxiorder',
            name='status',
            field=models.CharField(choices=[('searching', 'Пошук водія'), ('accepted', '🚕 Водій прийняв замовлення'), ('on_the_way', '🚗 Водій їде до вас'), ('arrived', '📍 Водій на місці'), ('completed', '✅ Замовлення виконано'), ('cancelled', 'Скасовано')], default='searching', max_length=20),
        ),
    ]
