# Generated by Django 5.2.5 on 2026-02-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_courierorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierorder',
            name='status',
            field=models.CharField(choices=[('created', 'Створено'), ('accepted', '📦 Курʼєр прийняв доставку'), ('on_the_way', '🚚 Курʼєр в дорозі'), ('arrived', '📍 Курʼєр на місці'), ('completed', '✅ Доставку завершено')], default='created', max_length=20),
        ),
    ]
