# Generated by Django 5.2.5 on 2026-03-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_courierorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxiorder',
            name='dest_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxiorder',
            name='dest_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxiorder',
            name='pickup_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxiorder',
            name='pickup_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
