# Generated by Django 5.2.5 on 2026-03-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0003_courierrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='courier_avatars//'),
        ),
    ]
