# Generated by Django 5.2.5 on 2026-03-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0004_courier_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='courier',
            name='bonus_for_paid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courier',
            name='rating_bonus_for_paid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courier',
            name='ride_500_for_paid',
            field=models.BooleanField(default=False),
        ),
    ]
